// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Ym3Qj4TTeSj4nhu39Xu-lYk8bQbN8Bw',
    appId: '1:1054697392631:web:a12600fa4325a995b786f2',
    messagingSenderId: '1054697392631',
    projectId: 'flutter-test-a1c0e',
    authDomain: 'flutter-test-a1c0e.firebaseapp.com',
    storageBucket: 'flutter-test-a1c0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCRA4YZSWO2xX5kasjf-ABNa1beDmo4XE',
    appId: '1:1054697392631:android:958864ee322cd9dab786f2',
    messagingSenderId: '1054697392631',
    projectId: 'flutter-test-a1c0e',
    storageBucket: 'flutter-test-a1c0e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs9-EUHxu4YzdWhsOtn4SYkIHsNNyfza8',
    appId: '1:1054697392631:ios:24357555de62237ab786f2',
    messagingSenderId: '1054697392631',
    projectId: 'flutter-test-a1c0e',
    storageBucket: 'flutter-test-a1c0e.firebasestorage.app',
    iosBundleId: 'es',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9-EUHxu4YzdWhsOtn4SYkIHsNNyfza8',
    appId: '1:1054697392631:ios:24357555de62237ab786f2',
    messagingSenderId: '1054697392631',
    projectId: 'flutter-test-a1c0e',
    storageBucket: 'flutter-test-a1c0e.firebasestorage.app',
    iosBundleId: 'es',
  );

}